mmg:
  mysql:
    # 数据库地址
    host: localhost
    # 数据库端口
    port: 3306
    # 数据库用户名
    user: root
    # 数据库密码
    password: 090j
    # 数据库的库名
    database: ycg_goods_test
  config:
    # 工程根路径的包名
    rootPackageName: com.ycg9.goods
    # 实体类的包名后缀
    entityPackageSuffix: entity
    # Mapper类的包名后缀
    mapperPackageSuffix: mapper
    # 生成Java文件时需要过滤掉的表名前缀（,分割）
    filterTablePrefix: ycg
    # 生成文件的主文件夹路径 为空时，默认为当前工程路径下的target/build/ 必须有结束的"/"
#    generatorRootPath: /Users/aoe/company/yunchuan/ycg9-goods/src/main/
